name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-berglas
      - name: Run tests
        uses: sudo-bot/action-shunit2@latest
        with:
          cli: test/tf-plan-post.test.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
