name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sigoden/install-binary@v1
        with:
          repo: GoogleCloudPlatform/berglas
          tag: v2.0.6
      - name: Run tests
        uses: sudo-bot/action-shunit2@latest
        with:
          cli: test/tf-plan-post.test.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
